apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-microservice-rust-demo
  description: "This is a tech demo of a Rust microservice orchestrated through the Backstage portal."
  tags:
  - migrate-to-cortex
spec:
  type: service
  lifecycle: experimental
  owner: guests
  dependsOn:
    - resource:default/microservice-db
  providesApis:
    - rust-demo-api
  implementsApis: []
