apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-microservice-rust-demo
  description: "This tech demo showcases a Rust microservice, demonstrating best practices in development, orchestration, and monitoring, all integrated within the Backstage portal."
  annotations:
    github.com/project-slug: jreock-cortex/cortex-microservice-rust-demo
    x-cortex-git: jreock-cortex/cortex-microservice-rust-demo
    x-cortex-tag: guests/backstage-microservice-rust-demo
    x-cortex-type: service
  tags:
    - migrate-to-cortex
    - rust
    - microservice
  links:
    - url: https://github.com/jreock-cortex/cortex-microservice-rust-demo/pulse
      title: Build Dashboard
      icon: dashboard
    - url: https://docs.example.com/backstage-microservice-rust-demo/getting-started
      title: Getting Started Guide
      icon: documentation
    - url: https://example.com/runbook/backstage-microservice-rust-demo
      title: Operational Runbook
      icon: book
    - url: https://monitoring.example.com/dashboard/backstage-microservice-rust-demo
      title: Monitoring Dashboard
      icon: graph
    - url: https://api.example.com/swagger-ui/backstage-microservice-rust-demo
      title: API Documentation
      icon: api
    - url: https://chat.example.com/teams/backstage-microservice-rust-demo
      title: Team Chat Room
      icon: chat
    - url: https://ci.example.com/builds/backstage-microservice-rust-demo
      title: CI Pipeline Status
      icon: ci
    - url: https://security.example.com/vulnerability-report/backstage-microservice-rust-demo
      title: Vulnerability Report
      icon: security
  x-cortex-link: 
    - Build Dashboard: https://github.com/jreock-cortex/cortex-microservice-rust-demo/pulse
    - Getting Started Guide: https://docs.example.com/backstage-microservice-rust-demo/getting-started
    - Operational Runbook: https://example.com/runbook/backstage-microservice-rust-demo
    - Monitoring Dashboard: https://monitoring.example.com/dashboard/backstage-microservice-rust-demo
    - API Documentation: https://api.example.com/swagger-ui/backstage-microservice-rust-demo
    - Team Chat Room: https://chat.example.com/teams/backstage-microservice-rust-demo
    - CI Pipeline Status: https://ci.example.com/builds/backstage-microservice-rust-demo
    - Vulnerability Report: https://security.example.com/vulnerability-report/backstage-microservice-rust-demo

spec:
  type: service
  lifecycle: experimental
  owner: guest
  dependsOn:
    - component:microservice-db
  implementsApis: []
  documentation:
    - title: Architecture Overview
      url: https://docs.example.com/backstage-microservice-rust-demo/architecture
    - title: Environment Setup
      url: https://docs.example.com/backstage-microservice-rust-demo/environment-setup
  support:
    - title: Support Slack Channel
      url: https://chat.example.com/channels/backstage-support
    - title: Email Support
      url: mailto:support@example.com
  technology:
    - name: Rust
      version: 1.50
      description: "The programming language used for development."
    - name: Docker
      version: 20.10
      description: "Containerization platform used for deployment." 
  x-cortex-owners:
    - name: guests
      type: group
      provider: CORTEX
  x-cortex-children: microservice-db
  x-cortex-groups:
    - migrate-to-cortex
    - rust
    - microservice
